USE [SLinkDB]
GO

/****** Object:  Table [dbo].[UrlRecords]    Script Date: 11/11/2019 9:31:53 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UrlRecords](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Hash] [nvarchar](32) NOT NULL,
	[OriginalUrl] [nvarchar](max) NOT NULL,
	[CreatedDate] [datetime] NOT NULL
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[UrlRecords] ADD  DEFAULT (getdate()) FOR [CreatedDate]
GO

/****** Object:  Index [OriginalUrl_index]    Script Date: 11/11/2019 9:57:16 AM ******/
CREATE NONCLUSTERED INDEX [Hash_index] ON [dbo].[UrlRecords]
(
	[Hash] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
